# Reads the measurements.xml every 10 seconds
sensor:
  - platform: rest
    resource: http://Stegagid_IP/measurements.xml
    json_attributes:
      - root
      - Measurements
    name: solar_inverter
    scan_interval: 10
    value_template: 'OK'
  - platform: integration
    name: energy_collected
    source: sensor.solar_live_output
    unit_prefix: k
    round: 2

# Specify the sensors and values
# Note XML starts from 0
# This is valid for StecaGrid 3203x
template:
    sensor:
      - name: "Live solar power" 
        unique_id: solar_live_output
        state: >
          {% set root = state_attr('sensor.solar_inverter', 'root') %}
          {% if root.Device.Measurements.Measurement[6]["@Value"] is defined %}
              {{ root.Device.Measurements.Measurement[6]["@Value"] | round(0)}}
          {% else %}
              0
          {% endif %}
        # 2023-02-11, ref https://community.home-assistant.io/t/energy-from-riemann-sum-integral-device-not-showing/390180/4
        device_class: energy
        unit_of_measurement: 'W'
        state_class: measurement
        # 2023-02-11, ref https://community.home-assistant.io/t/how-to-enable-power-consumption-statistics/327102/13
        attributes:         
          last_reset: '1970-01-01T00:00:00+00:00'
      - name: "Inverter temperature"
        unique_id: inverter_temperature
        state: >
          {% set root = state_attr('sensor.solar_inverter', 'root') %}
          {% if root.Device.Measurements.Measurement[15]["@Value"] is defined %}
              {{ root.Device.Measurements.Measurement[15]["@Value"] | round(0)}}
          {% else %}
              0
          {% endif %}
        device_class: temperature
        unit_of_measurement: 'C'